### ISSUE TITLE
Generating snp file for CAST/EiJ  x C57BL/6J ?

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#13]
Hi Tan,
Is there a way to obtain `phased.snp.tsv` file from `mgp.v5.merged.snps_all.dbSNP142.vcf.gz` file for the mentioned mouse strains? If so, how?
I am trying to expand my `vcf.gz` file but it fails to expand?!
```
Taraks-MacBook-Pro:downloads tarakshisode$ gunzip mgp.v5.merged.snps_all.dbSNP142.vcf.gz
gunzip: mgp.v5.merged.snps_all.dbSNP142.vcf.gz: unexpected end of file
gunzip: mgp.v5.merged.snps_all.dbSNP142.vcf.gz: uncompress failed
```

**Comment by tanlongzhi** [comment]
Hi Tarak,

A while ago I added an example script `scripts/snp_sanger_cast_b6.py` that does just that.

I'm not sure about the corruption problem, though. You can consider download the file again, or contact Sanger.

**Comment by tarak77** [comment]
Oh cool. 
I did try many times but no success. Will it be possible for you to provide it in the GEO database, from where I can try downloading it?

**Comment by tanlongzhi** [comment]
Have you tried just downloading one strain, [CAST](ftp://ftp-mouse.sanger.ac.uk/current_snps/strain_specific_vcfs/CAST_EiJ.mgp.v5.snps.dbSNP142.vcf.gz)? That much smaller file should suffice.

**Comment by tanlongzhi** [comment]
Btw to check file integrity, you don't need to actually decompress the file (especially since these are huge files). You only need to run `gunzip -t <file.gz>`. If the output is nothing, the file is good.

**Comment by tarak77** [comment]
Yes, I just downloaded the CAST_Eij strain file and its index. Does the `scripts/snp_sanger_cast_b6.py` work with just these files?

The integrity for `mgp.v5.merged.snps_all.dbSNP142.vcf.gz` fails but its good for `CAST_EiJ.mgp.v5.snps.dbSNP142.vcf.gz`

**Comment by tanlongzhi** [comment]
I don't know. Do you want to give it a try? Also, the script is very simple; you can also try modifying it in case it doesn't work.

**Comment by tarak77** [comment]
Ok so I kinda understand what the script is doing. I use pysam to print the header and try to get a feel of the .vcf file. So in CAST_EiJ and other strains, the default reference allele is C57BL/6J strain?

**Comment by tanlongzhi** [comment]
Yes C57BL/6J is the mouse reference genome.

**Comment by tarak77** [comment]
Also is 1 and chr1 equivalent in dip-c and Hickit?

**Comment by tanlongzhi** [comment]
They are not the same for dip-c.

Not sure about hickit. @lh3 will be the best person to answer that.

**Comment by tarak77** [comment]
I see, dip-c uses `1` to denote _chromosome 1_  in the phased_SNP file, while its `chr1` in hickit. Thanks!

**Comment by lh3** [comment]
No, 1 and chr1 are not the same. All files shall be consistent about the chromosome naming, or you will get wrong results.

**Comment by tarak77** [comment]
Ok, when I use grep for seeing all the chromosomes, I get 
```
>chr1 1
>chr2 2
>chr3 3
>chr4 4
>chr5 5
>chr6 6
>chr7 7
>chr8 8
>chr9 9
>chr10 10
>chr11 11
>chr12 12
>chr13 13
>chr14 14
>chr15 15
>chr16 16
>chr17 17
>chr18 18
>chr19 19
>chrX X
>chrY Y
>chrM MT
>CAST_EI_MMCHR11_CTG4 CAST_EI_MMCHR11_CTG4
>CAST_EI_MMCHR11_CTG5 CAST_EI_MMCHR11_CTG5
>GL456210.1 GL456210.1
>GL456211.1 GL456211.1
>GL456212.1 GL456212.1
>GL456213.1 GL456213.1
>GL456216.1 GL456216.1
>GL456219.1 GL456219.1
>GL456221.1 GL456221.1
>GL456233.1 GL456233.1
>GL456239.1 GL456239.1
>GL456350.1 GL456350.1
>GL456354.1 GL456354.1
>GL456359.1 GL456359.1
>GL456360.1 GL456360.1
>GL456366.1 GL456366.1
>GL456367.1 GL456367.1
>GL456368.1 GL456368.1
>GL456370.1 GL456370.1
>GL456372.1 GL456372.1
>GL456378.1 GL456378.1
.
.
```

**Comment by tanlongzhi** [comment]
Looks like this genome FASTA is using chr1 instead of 1.

**Comment by tarak77** [comment]
Right,
Also how long does the preprocessing and alignment step take in general? I am running my data and its taking many hours? is that normal

**Comment by tarak77** [comment]
A quick question, I am running dip-c for my new data and currently I am at the step to generate the `.seg` file. I want to run hickit too to check whether it saves time? How should I convert my `.bam` file from dip-c to `.sam` to use in hickit?

**Comment by tanlongzhi** [comment]
Hickit is much faster. To save time, you can run all the preprocessing with hickit, and use `scripts/hickit_pairs_to_con.sh` to convert into dip-c's `.con` format.

I don't think it's worth it to convert `.bam` back into `.sam.gz`.

**Comment by tarak77** [comment]
Okay
