### ISSUE TITLE
Regarding exp.py

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#18]
Hi @tanlongzhi ,
In exp,py, will it possible to include an option for translating the chromosomes instead of the two homologs separately? I mean instead of finding the centers of each homolog, can we find the centers of the homolog pair and then translate.

**Comment by tanlongzhi** [comment]
Hi Tarak,

Unfortunately, `dip-c exp` currently doesn't offer this function.

However, you can easily manipulate `.3dg` files yourself. The [format](https://github.com/tanlongzhi/dip-c#3dg) is extremely simple, whose columns 3-5 can be directly modified with any software. It's a plain-text format whose ordering of lines doesn't matter.

**Comment by tarak77** [comment]
Happy thanksgiving @tanlongzhi ! 
I see, I was looking at `pymol_movie_exp.py` script for making a movie. I understand it now: extracting each chromosome as a separate object and then defining the timeframe for movie and translating and then rotating it.

I was trying to modify it so that in my movie:
->First 360deg loop shows us the whole genome
->second loop shows just the chromosome1(maternal and paternal) and hides the other chromosomes
->third loop shows just chromosome2(mat and pat) and hides others
->forth loop shows just chromosome3(mat and pat)...
......
->last loop shows just chromosome X and Y

I was playing with the script but I couldn't get the frames setting right and get what I want.
I would really appreciate if you could help me with the rough template for the task above?

Hope to hear from you soon!

**Comment by tanlongzhi** [comment]
Happy holidays Tarak!

I'm afraid that my knowledge about PyMol is not sufficient to answer your question. My script was put together after trials and errors, without much understanding. You can probably ask for help from structural biologists, who should be experts on PyMol.

For your purpose, I'd probably do each loop separately, and then concatenate the movies afterwards.

**Comment by tarak77** [comment]
Sure, ill try out doing them separately. Thanks!

**Comment by tarak77** [comment]
I somehow managed to get the movie using one script. I defined scenes for different tasks.

**Comment by tanlongzhi** [comment]
Happy to hear! Best wishes on moving directing!
