### ISSUE TITLE
Highlighting centromeres in the model?

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#20]
Hey @tanlongzhi,
Is there a way to highlight the centromere positions in the movie of the 3D models for human/mouse? I ask that because it may help us determine the cell cycle phase.

**Comment by tarak77** [comment]
Awesome! 
Quick question:
1. How did you obtain the centromere coordinates? I have been searching for mm10 centromere coordinates on UCSC browser but no luck yet! Any help?

**Comment by tanlongzhi** [comment]
I think I used UCSC Genome Browser's Table Browser, and selected something like "assembly gaps". In the gap file, some lines corresponds to centromeres with start and end coordinates. I simply picked the midpoints.

If that doesn't work for you, alternatively, for mouse you can probably just use zero as all centromere coordinates.

**Comment by tanlongzhi** [comment]
Oh I didn't realized that I forgot to upload my mm10 centromere files, used in the publication. I just updated this repo (cb19e6ad1c4e7a18c3ace28ba0cbf107452d67c2) to include that.

**Comment by tarak77** [comment]
Great!, But in this file mm10 gap file:
[Galaxy12-[UCSC_Main_on_Mouse__gap_(genome)].txt](https://github.com/tanlongzhi/dip-c/files/2622005/Galaxy12-.UCSC_Main_on_Mouse__gap_.genome.txt)
the centromere coordinates same for all chromosomes? why is that so?

Interesting, I don't get why using zero will work?

**Comment by tanlongzhi** [comment]
According to my understanding, all mouse centromeres are at the very beginning of chromosomes (called "telocentric"), and therefore should have *similar* start and end coordinates. I guess mm10 set them to be the *same* as an approximation. You can probably ask an expert on this.

Since each telomere-centromere is completely unmappable, it doesn't really matter where one sets the midpoint coordinate.

**Comment by tarak77** [comment]
I was trying to implement the script, but get an error:

```
(py27) wg-dhcp174d191d007:dip-c tarakshisode$ paste mm10.cen.hom.name mm10.cen.hom.color ./test_cells/4CSE/M_4CSE-1/cell.cen.pos | python ./scripts/name_color_x_y_z_to_cif.py /dev/stdin > ./test_cells/4CSE/M_4CSE-1/cell.cen.n.cif
Traceback (most recent call last):
  File "./scripts/name_color_x_y_z_to_cif.py", line 42, in <module>
    b_factor = float(cen_tel_file_line_data[1]) # column 2: color -> b_factor
ValueError: could not convert string to float: chr1
```

**Comment by tanlongzhi** [comment]
The color values must be real numbers, not strings.

For mouse, you can remove the string prefix `chr` and replace the sex chromosomes `X` and `Y` with `20` and `21` by running:
```
awk 'BEGIN{FS="\t"}{print $1;print $1}' color/mm10.chr.cen | sed 's/chr//g; s/X/20/g; s/Y/21/g' > mm10.cen.hom.color
```

You can find examples of such human-mouse difference (hg19 versus mm10) in data treatment in the provided scripts `scripts/con_to_matlab_human.sh` versus `scripts/con_to_matlab_mouse.sh`.

**Comment by tanlongzhi** [comment]
According to my understanding of PyMol, the sphere size is not controlled by the mmCIF file.

I typically formatted by typing the following in PyMol, assuming the centromere file is called `cen.cif`:
```python
set sphere_scale, 3, cen
```

**Comment by tarak77** [comment]
Awesome!
