### ISSUE TITLE
SNP information for reproducing the analysis

### ISSUE THREAD

**Issue by kainblue** [tanlongzhi/dip-c#27]
Hi Longzhi,

Is the NA12878.txt.gz under snps folder the correct file for imputing Gm12878 single cell hic? Or it is just an example file? If it is the case, do you mind share the full SNP information?

Thanks

Bo

**Comment by tanlongzhi** [comment]
Hi Bo,
Yes, that's the file we used for analysis. Note that Illumina released updated versions afterwards.
Best,
Tan

**Comment by kainblue** [comment]
Hi Longzhi,

Thank you so much!

Bo
