### ISSUE TITLE
How to pileup interchromosomal contact maps?

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#31]
Hey @tanlongzhi ,
Hope you are doing good!
In your analysis of interchromosomal and long-range intrachromosomal contacts, how did you pileup the inter chromosomal contact maps to generate the super elliptical neighbourhood region? Because the dimensions for each chromosomes are different, I don't know how to overlay the haplotype resolved inter chromosomal contact maps?

Any help will be great!

**Comment by tanlongzhi** [comment]
Hey @tarak77, hope all is well for you too.

Pile-up of contact maps is done with `dip-c ard`. I think a typical pile-up contact "map" (2D histogram of contacts, as in Fig. S7A) can be generated with something like:
```sh
dip-c ard -d10000000 -h200000 in.con > in.inter.d10M_h20k.ard
```

I'll write more details on the README page.

**Comment by tarak77** [comment]
That would be awesome @tanlongzhi !!!
