### ISSUE TITLE
change resolution from .3dg file

### ISSUE THREAD

**Issue by lidaof** [tanlongzhi/dip-c#35]
Hi Tan @tanlongzhi , I downloaded some .3dg file from your GEO repository, i found most of them are based on 20kb resolution.
Is it possible I can convert them to 40kb, 80kb without remodeling? i was thinking if convert to 40kb for example, we can use the center point of 2 points (atoms) from 20kb file? does this make sense?

**Comment by tanlongzhi** [comment]
Hi @lidaof, you're right that we only kept the 20-kb files for all cells. I think the results will be different between a normal 40-kb run and a back-calculated one; you can try a few cells and compare. I suspect problems especially with length scaling.

As a side note, 3D modeling to 40 kb (or 80 kb) is very fast with the current hickit pipeline, and is much faster than running to full 20 kb. So it won't take long if you re-run.

**Comment by lidaof** [comment]
Hi @tanlongzhi thanks for reply. seems back calculation may not a good choice.
Do you know which tool can compare 2 3d models?
Thanks again

**Comment by tanlongzhi** [comment]
No problem. You can use `dip-c align` to align (via rotation, translation, and/or mirror image) multiple 3D models. This should make visual comparison easier in PyMol.

**Comment by lidaof** [comment]
Thank you @tanlongzhi !
