### ISSUE TITLE
In the old pipeline, Is it possible to generate models at a higher resolution?

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#36]
Hey @tanlongzhi ,
Will it be possible to pass in particle size list with resolutions higher than 20kb? what would cause it to fail?
Thanks!

**Comment by tanlongzhi** [comment]
Hey @tarak77, yes it should work but will be much slower. Keep in mind that the time complexity to keep track of particles is O(N) and even worse for exclusion volumes (collision detection).

**Comment by tarak77** [comment]
Now that I am thinking, do you have any idea for an efficient method for collision detection?

**Comment by tanlongzhi** [comment]
Hi @tarak77, yes, @lh3 has already developed an efficient method using AVL tree. This has been implemented as the 3D modeling functionality of [hickit](https://github.com/lh3/hickit). More specifically, the relevant files are [fdg.c](https://github.com/lh3/hickit/blob/master/fdg.c) and [kavl.h](https://github.com/lh3/hickit/blob/master/kavl.h) (also see [kavl.h](https://github.com/attractivechaos/klib/blob/master/kavl.h) in [klab](https://github.com/attractivechaos/klib)).

Therefore, for high-resolution 3D modeling, I'd recommend [hickit](https://github.com/lh3/hickit) to save time.

**Comment by tarak77** [comment]
Okk, thanks!
