### ISSUE TITLE
Using align.py

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#38]
Hey @tanlongzhi ,
How would one use the align.py script? What all inputs can we give and what outputs can we get?
Is it possible to get a genome wide RMSD score?

Thanks!

**Comment by tanlongzhi** [comment]
Hey @tarak77, the `align` functionality can be used as following:
```sh
dip-c align -o aligned. a.3dg b.3dg. c.3dg
```
The inputs are any numbers of `.3dg` files. In the above example, we input 3 files (0th: `a.3dg`, 1st:`b.3dg`, 2nd: `c.3dg`). There're two outputs:
1. The standard error gives RMSD values between each pair of inputs (in this case, 3 pairs), and an overall RMSD value (shown following `RMS RMSD: `, which is the r.m.s. of all RMSDs). Note that RMSDs are only calculated for particles common to *all* input files.
2. Each input file is also aligned to each other input file. In the above example, one such output file, `aligned.0_to_2.3dg`, is the result of aligning the 0th input file (`a.3dg`) to the 2nd input file (`c.3dg`). Note that each output file contains *all* particles in original input file, even if some are not present in the input file that it aligns to.

**Comment by tarak77** [comment]
Ok I see. thanks
