### ISSUE TITLE
hickit: invalid option -- 'M'

### ISSUE THREAD

**Issue by conchoecia** [tanlongzhi/dip-c#40]
I ran the tutorial `hickit -s${rep} -M -i` ... et cetera and got the following error:  `hickit: invalid option -- 'M'`

Looks like `-M` is no longer an option for `hickit`. Do you know what its purpose was in this command? Thanks!

**Comment by tanlongzhi** [comment]
You need to download the latest version (0.1.1) of hickit. The older version (0.1) does not have this option.

**Comment by conchoecia** [comment]
pulling the latest version of `hickit` and running `make` fixed the issue. Thank you for the quick response!
