### ISSUE TITLE
Is variant masked genome ref required for the alignment ?

### ISSUE THREAD

**Issue by yuxuth** [tanlongzhi/dip-c#41]
Thanks for providing this awesome tool! 

I just want to double-check do I need to use variant masked genome ref when doing the alignment?  That's what I read in some allele-specific analysis paper. 
Sorry, I do not fully understand how hickit.js resolve the phrase. 
Thanks!

**Comment by tanlongzhi** [comment]
Thank you for your kind words. A variant-masked genome reference is not needed. In fact, the aligner (BWA) cannot accept N-masking information anyway.

**Comment by yuxuth** [comment]
Thank you for the prompt reply!
