### ISSUE TITLE
Question about SNP file

### ISSUE THREAD

**Issue by AIBio** [tanlongzhi/dip-c#44]
Hi,

I want to perform Dip-C for home-made cell line. We don't have the SNP information in this cell line. So, I have two questions: 

1. In this case, do we need to do whole-genome sequencing of the cell line-derived parent and identify paternal- and maternal-specific SNP information?
2. I have read method part ("Generation of a List of Phased SNPs") in the paper ("Three-dimensional genome structures of single diploid human cells").  The SNP information of GM12878 and PBMCs cell lines are well-annotated. Can I use the SNP information of these two cell lines?

Best wishes

Hanwen

**Comment by tanlongzhi** [comment]
Hi Hanwen,

Thank you for your interest in our work. Yes, Dip-C currently requires fully phased SNPs across the genome, which must be obtained for each donor. In our previous work, this was achieved by sequencing additional family members (e.g., parents of the PBMC donor). If family is not feasible, you may have to use other existing assays to phase the donor genome first.

Best,
Tan

**Comment by AIBio** [comment]
> 

Hi longzhi,

Thank you for your help. We will re-design our experiments.

Best,
Hanwen
