### ISSUE TITLE
The coordinate system of SNP file.

### ISSUE THREAD

**Issue by AIBio** [tanlongzhi/dip-c#45]
Hi Longzhi,

@tanlongzhi 

I sorry to bother you again.
Our approach to recording a base in the genome can be divided into two group: 0-base or 1-base.
I would like to know the coordinate system used by the SNP file you provided in Github.

Best wishes~
Hanwen

**Comment by tanlongzhi** [comment]
Hi @AIBio, no problem at all. Glad to help! The file should be 1-based, because it's converted from VCF files (some example conversion scripts for mice can be found in `scripts/snp_*.py`.

**Comment by AIBio** [comment]
> 

Thank you very much!
