### ISSUE TITLE
Finding m independent models for further analysis?

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#5]
Hi Tan,
The models look great and a single model is good for visualization purposes. I remember that in the paper you did analysis on some more replicates to get the results. And nuc_dynamics has -m options to define the number of models we wish to find. Thinking along the same lines, can we specify the number of independent models to be generated using dip-c/ hickit?? Say for each diploid single cells I want 100 models so as to do analysis on structural positioning or pairwise distance distributions between loci??

**Comment by tanlongzhi** [comment]
Hi Tarak,

Currently this repo does not provide an automatic function to generate replicates.

However, replicates can be easily generated by copying both `impute.con.gz` (the output of `dip-c impute`) and `clean.con.gz` (the output of an earlier step, `dip-c clean`) to many different folders, and run all the subsequent steps separately for each folder.

When running replicates, please make sure that the random seeds of `nuc_dynamics` (the 3D modeling tool used in this repo) are different for different replicate folders. If using the default seed of `nuc_dynamics` (based on time), please make sure to start different replicates at different times. This was how we did it for the Dip-C paper. Alternatively, if using an user-specified seed, please specify a different seed for each replicate folder.

**Comment by lh3** [comment]
For hickit, `-s` sets the random seed. Just use something like
```sh
seq 100 | xargs -i echo hickit -s {} ... -O out-{}.3dg
```
to generate 100 command lines.
