### ISSUE TITLE
Error while visualizing contact files using juicebox

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#6]
Hi Tan,

I was trying to visualize one of the diploid cell contacts with and without haplotype imputation using the Juicebox tool. The haplotype-resolved .con file gives a visualization but the without haplotype resolved .con file gives me the following error:
```
wg-dhcp174d163d001:fraser-lab tarakshisode$ java -Xmx2g -jar juicer_tools.1.7.6_jcuda.0.8.jar pre -n ../dip-c/CDX1-413.20k/GSE117109_GSM2476407_1CDX1-413.dedup.juicer.txt.gz ../dip-c/CDX1-413.20k/1CDX1-413.dedup.hic mm9
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1472)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1243)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:656)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:378)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:286)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:105)
	at juicebox.tools.HiCTools.main(HiCTools.java:98)
```

Am I doing something wrong?

I have attached the deduce.juicer.txt.gz file, just in case
[GSE117109_GSM2476407_1CDX1-413.dedup.juicer.txt.gz](https://github.com/tanlongzhi/dip-c/files/2393881/GSE117109_GSM2476407_1CDX1-413.dedup.juicer.txt.gz)

**Comment by tanlongzhi** [comment]
I just tested visualization on the same file; and it worked well. Please see screenshot below:
<img width="645" alt="2018-09-18 4 45 41" src="https://user-images.githubusercontent.com/2436999/45715587-95d8c280-bb62-11e8-8dd6-d5dabfbbfe0b.png">

In contrast, your `.juicer.txt.gz` file is somehow empty. Can you provide your command and input file to generate that file?

Btw, after you generate a good `.juicer.txt.gz` file, you should use `mm10` instead of `mm9` in the juicer_tools step, because I mapped those reads to mm10 coordinates.

**Comment by tarak77** [comment]
I actually used the same command as in the repo

`wg-dhcp174d163d001:dip-c tarakshisode$ ./con_to_juicer_pre_short.sh ./CDX1-413.20k/GSE117109_GSM2476407_1CDX1-413.dedup.con.gz`

Ok I will use mm10

**Comment by tanlongzhi** [comment]
I just tested this command both on macOS High Sierra and on CentOS 7. Below is the `.juicer.txt.gz` file that I generated. You can see its content; I'm not sure what led to your empty file.

[GSE117109_GSM2476407_1CDX1-413.dedup.juicer.txt.gz](https://github.com/tanlongzhi/dip-c/files/2395161/GSE117109_GSM2476407_1CDX1-413.dedup.juicer.txt.gz)

**Comment by tarak77** [comment]
I see now, there might be some issue when I downloaded the file. Thanks!
