### ISSUE TITLE
Can not colored

### ISSUE THREAD

**Issue by XiongGZ** [tanlongzhi/dip-c#60]
Hi Tan, @tanlongzhi 

When i try to colored the chromosomes and cpg island, the command run successfully, but can not write the colors.
Can you help me to solve this problem?

**Commond:**
`dip-c color -c $dip_c/color/mm10.cpg.20k.txt patski.G2M.3dg`

**patski.G2M.3dg:**
![image](https://github.com/tanlongzhi/dip-c/assets/63765061/d271700d-7eb9-4194-9fde-ed95a8724f71)

**mm10.cpg.20k.txt:**
![image](https://github.com/tanlongzhi/dip-c/assets/63765061/9f51f064-0625-4715-a89f-afdd70f4d25e)

**Results:**
![image](https://github.com/tanlongzhi/dip-c/assets/63765061/5e78cf8b-33bb-4b1f-9bbc-2762a41e3592)

**Comment by tanlongzhi** [comment]
Looks like your genome reference file for mapping (and hence your .3dg file) has chromosomes named like "Y", while my color files have the mouse chromosomes named like "chrY", causing a mismatch.

**Comment by XiongGZ** [comment]
> Looks like your genome reference file for mapping (and hence your .3dg file) has chromosomes named like "Y", while my color files have the mouse chromosomes named like "chrY", causing a mismatch.

I deleted the chromosome Y and X, but it still don't work
`grep -v -E "^Y|^X" patski.G2M.3dg > test.3dg`

**test.3dg:**
![image](https://github.com/tanlongzhi/dip-c/assets/63765061/dc49c07d-76c6-4418-864d-34df3f0871b9)

**Command:**
`dip-c color -c $dip_c/color/mm10.cpg.20k.txt test.3dg`

**Result:**
![image](https://github.com/tanlongzhi/dip-c/assets/63765061/0b2bebe0-1318-495b-bcf3-5c4cf019553b)

**Comment by tanlongzhi** [comment]
There will still be mismatch like "13" vs "chr13". You must rename all your chromosomes.

**Comment by XiongGZ** [comment]
> There will still be mismatch like "13" vs "chr13". You must rename all your chromosomes.

It worked. Thanks!
