### ISSUE TITLE
Help with regenerating fig 2A from paper

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#7]
Hi Tan,
This may seem a random question, but I have seen in many papers before where there are movies of chromosome expanding/exploding from the genome structures just to make the visualization more appealing. I noticed that you too have the expand/explode figure 2A in your paper. Could you share how to generated those models, i.e. is there a way to expand/explode the genome model so as to clearly see each of the chromosomal pairs ?

**Comment by tanlongzhi** [comment]
Hi Tarak,
You're not the only one asking. Please refer to this [new section](https://github.com/tanlongzhi/dip-c#exp_chr) of the README.

**Comment by tarak77** [comment]
Great,, we really appreciate it! 
One last question with the movie generation, I understand the .py script when pasted in the pymol command we get the expanded genome structure. How to actually save those frames during each chr extraction to expansion in order to get the .mov file?

**Comment by tanlongzhi** [comment]
An example movie script, link to the movie, and instructions are now added (ae896ea5266815dbfbb941fb2790afe9d3d2afe4).

**Comment by tarak77** [comment]
very awesome!!!
